services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nestjs-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb:
